[project]
name = "rm-bias"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "torch>=2.8.0",
    "transformers>=4.55.4",
]

[tool.uv]
no-build-isolation-package = ["flash-attn"]

[tool.uv.sources]
dictionary-learning = { workspace = true }

[tool.uv.workspace]
members = [
    "dictionary_learning",
]

[tool.ruff.lint]
ignore = ["E402", "F403", "F722", "F821"]
